version: 2
jobs:
  validate_terraform:
    environment:
        AWS_DEFAULT_REGION: us-east-1
    docker:
      - image: hashicorp/terraform:light
    steps:
      - checkout
      - run:
          name: Install curl
          command: apk add --update curl && apk upgrade
      - run:
          name: terraform init
          command: find . -type f -name "*.tf" -exec dirname {} \;|sort -u | while read m; do (cd "$m" && terraform init -input=false -backend=false) || exit 1; done
      - run:
          name: Validate Terraform configurations
          command: find . -name ".terraform" -prune -o -type f -name "*.tf" -exec dirname {} \;|sort -u | while read m; do (cd "$m" && terraform validate && echo "√ $m") || exit 1 ; done
      - run:
          name: Check if Terraform configurations are properly formatted
          command: if [[ -n "$(terraform fmt -write=false)" ]]; then echo "Some terraform files need be formatted, run 'terraform fmt' to fix"; exit 1; fi
      - run:
          name: Install tflint
          command: curl -L -o /tmp/tflint.zip https://github.com/terraform-linters/tflint/releases/download/v0.13.2/tflint_linux_amd64.zip && unzip /tmp/tflint.zip -d /usr/local/bin
      - run:
          name: Check Terraform configurations with tflint
          command: find . -name ".terraform" -prune -o -type f -name "*.tf" -exec dirname {} \;|sort -u | while read m; do (cd "$m" && tflint && echo "√ $m") || exit 1 ; done
  lint_handler:
    environment:
      AWS_DEFAULT_REGION: us-east-1
    docker:
      - image: circleci/golang:latest
    working_directory: /go/src/github.com/GSA/grace-inventory
    steps:
      - checkout
      - run:
          name: Lint Handler
          command: make lint_handler
  integration_test:
    environment:
      AWS_DEFAULT_REGION: us-east-1
      TF_LOG: DEBUG
    docker:
      - image: circleci/golang:latest
    steps:
      - checkout
      - run:
          name: Install make, curl, unzip
          command: |
            sudo apt-get update
            sudo apt-get install -y make curl unzip
      - run:
          name: Install Terraform
          command: |
            TERRAFORM_LATEST_URL=$(curl --silent --location --head --output /dev/null --write-out '%{url_effective}' -- https://github.com/hashicorp/terraform/releases/latest)
            TERRAFORM_VERSION=${TERRAFORM_LATEST_URL##*/}
            TERRAFORM_VERSION=${TERRAFORM_VERSION:1:${#TERRAFORM_VERSION}}
            curl -o terraform.zip -sSL "https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_amd64.zip"
            sudo unzip terraform.zip -d /bin
            sudo chmod +x /bin/terraform
      - run:
          name: Install Moto Server
          command: |
            sudo apt-get install -y python3-dev gcc python3-pip
            sudo pip3 install --upgrade pip setuptools flask "moto[server]"
      - run:
          name: Test Terraform
          command: |
            make integration_test
  test_handler:
    docker:
      - image: circleci/golang:latest
    working_directory: /go/src/github.com/GSA/grace-inventory
    steps:
      - checkout
      - run:
          name: Run Unit Tests
          command: make test_handler
  release_handler:
    docker:
      - image: circleci/golang:latest
    working_directory: /go/src/github.com/GSA/grace-inventory
    steps:
      - checkout
      - run:
          name: Release handler
          command: make release_handler
      - persist_to_workspace:
          root: .
          paths:
            - ./release/*
  tfsec:
    docker:
      - image: circleci/golang:latest
    steps:
      - checkout
      - run:
          name: Install tfsec
          command: env GO111MODULE=on go get -u github.com/liamg/tfsec/cmd/tfsec
      - run:
          name: Terraform static code analysis with tfsec
          command: tfsec
workflows:
  version: 2
  build:
    jobs:
      - validate_terraform
      - tfsec
      - lint_handler
      - test_handler
      - integration_test
      - release_handler:
          filters:
            tags:
              only: /^v.*/
            branches:
              only: master
